# version: '3.8'

services:
  rbnics-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vsc-rbnics-server
    user: root
    volumes:
      - .:/home/rbnics/shared
    working_dir: /home/rbnics/shared
    environment:
      - "PYTHONUNBUFFERED=1"
    command: tail -f /dev/null